version: 2
jobs:
  build:
    working_directory: /go/src/github.com/docker/swarmkit
    environment:
      # Needed to install protoc
      PROTOC: https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip

    # Note(cyli): We create a tmpfs mount to be used for temporary files created by tests
    # to mitigate the excessive I/O latencies that sometimes cause the tests to fail.
    # See https://github.com/docker/swarmkit/pull/2254.

    # There is no way to mount tmpfs volumes in the docker executor, so we are using
    # the machine executor. However, this incur a performance overhead
    # (https://discuss.circleci.com/t/using-docker-compose-in-2-0/9492/4)
    # and in the future could incur additional pricing changes
    # (https://circleci.com/docs/2.0/executor-types/#using-machine).

    # One possible hack is the following:

    # /dev/shm in the container is tmpfs although files in /dev/shm are not executable.
    # If we specify TMPDIR=/dev/shm, /dev/shm will be used by our tests, which call
    # ioutil.TempDir/ioutil.TempFile, to write temporary files.
    # We can also specify GOTMPDIR=/tmp or some other non-tmpfs directory
    # (see https://golang.org/doc/go1.10#goroot) - this is the directory in which the
    # go tool itself will put temporarily compiled test executables, etc.

    # However, using this hack still resulted in WAL test failures, so it seems like
    # it does not work.  It may be something to explore again if the penalty for
    # using the machine executor becomes unacceptable.

    docker:
    - image: circleci/golang:1.10.2

    steps:
    - checkout

    - run:
        name: Output debugging information
        command: |
            go version
            env

    # - run:
    #     name: Install protoc
    #     command: |
    #         wget -O "$HOME/$(basename $PROTOC)" "$PROTOC"
    #         unzip -o "$HOME/$(basename $PROTOC)" -d "$HOME"
    #         sudo cp -R "$HOME/include/google" /usr/local/include
    #         sudo chmod 777 -R /usr/local/include/google
    #         sudo cp -R "$HOME/bin/protoc" /usr/local/bin
    #         sudo chmod 777 /usr/local/bin/protoc

    # - run:
    #     name: Install test/lint dependencies
    #     command: make setup

    # - run:
    #     name: Validate dependency vendoring
    #     command: |
    #         git fetch origin
    #         if test -n "`git diff --stat=1000 origin/master | grep -E \"^[[:space:]]*vendor\"`"; then
    #             make dep-validate;
    #         fi

    # - run:
    #     name: Compile/lint/vet/protobuf validation
    #     command: make check binaries checkprotos

    - run:
        name: Run unit tests
        command: |
            GOTMPDIR=/tmp TMPDIR=/dev/shm make coverage

    - run:
        name: Run integration tests
        command: |
            # TMPFS has already been set up previously in the unit test step
            GOTMPDIR=/tmp TMPDIR=/dev/shm make coverage-integration

    # - run:
    #     name: Push coverage info to codecov.io
    #     command: bash <(curl -s https://codecov.io/bash)
