version: '3'
namespace: monitoring

services:
    cadvisor:
        image: google/cadvisor:v0.22.0
        mode: global
        update:
            parallelism: 1
            delay: 10s
        ports:
            - name: cadvisor
              protocol: tcp
              port: 8080
        mounts:
            - type: bind
              source: /
              target: /rootfs
            - type: bind
              source: /var/run
              target: /var/run
              writable: true
            - type: bind
              source: /sys
              target: /sys
            - type: bind
              source: /var/lib/docker/
              target: /var/lib/docker
