version: '3'
namespace: hello-world

services:
  ping:
      image: alpine
      command: ["sh", "-c", "ping google.com"]
      instances: 2
      placement:
          constraints:
              - node.name!=node-2
