version: '3'
namespace: voting-app

services:
    frontend:
        image: aluzzardi/s2_frontend
        instances: 1
        env:
            - QUEUE_HOSTNAME=redis
            - OPTION_A=Cats
            - OPTION_B=Dogs
        networks:
            - mynetwork
        ports:
            - name: front
              protocol: tcp
              port: 80

    redis:
        image: redis
        networks:
            - mynetwork

    worker:
        image: mikegoelzer/s2_worker:latest
        instances: 1
        networks:
            - mynetwork

    results:
        image: mikegoelzer/s2_results:latest
        instances: 1
        networks:
            - mynetwork
        ports:
            - name: results
              protocol: tcp
              port: 8080
        env:
            - PORT=8080

    pg:
        image: postgres:latest
        instances: 1
        networks:
            - mynetwork
        ports:
            - name: pg
              protocol: tcp
              port: 5432
        env:
            - POSTGRES_PASSWORD=pg8675309


# TODO(aluzzardi): For now we have to manually run `swarmctl network create --name mynetwork`
networks:
    mynetwork:
        driver: overlay
