version: '3'
namespace: voting-app

services:
    frontend:
        image: aluzzardi/s2_frontend
        env:
            - QUEUE_HOSTNAME=redis
            - OPTION_A=Cats
            - OPTION_B=Dogs
        networks:
            - mynetwork
        ports:
            - name: front
              protocol: tcp
              port: 80

    redis:
        image: redis
        networks:
            - mynetwork

# TODO(aluzzardi): For now we have to manually run `swarmctl network create --name mynetwork`
networks:
    mynetwork:
        driver: overlay
